name: Test Rust Project

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - name: Checkout repository
        uses: actions/checkout@v4

      # Set up Node.js for building AssemblyScript
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Build the AssemblyScript project
      - name: Build AssemblyScript Project
        run: |
          cd examples/helloworld
          npm install
          npm run asbuild

      # Build the Rust project
      - name: Test Rust Project
        run: cargo build --release

      # Test the Rust project
      - name: Test Rust Project
        run: cargo test --all
