name: Test AssemblyScript Project

on:
  push:
    paths:
      - 'examples/helloworld/**'
  pull_request:
    paths:
      - 'examples/helloworld/**'

jobs:
  test-assemblyscript:
    runs-on: ubuntu-latest

    steps:
      # Check out the code
      - name: Checkout repository
        uses: actions/checkout@v3

      # Set up Node.js
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '16'

      # Install dependencies
      - name: Install dependencies
        run: |
          cd examples/helloworld
          npm install

      # Build WASM
      - name: Compile AssemblyScript to WASM
        run: |
          cd examples/helloworld
          npm run asbuild
